version: '3.8'

services:
  aegis-gate:
    build: .
    container_name: aegis_gate_firewall
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - /app/__pycache__
    environment:
      - REDIS_URL=redis://redis:6379/0
      - UPSTREAM_URL=http://host.docker.internal:8080
    depends_on:
      - redis
    networks:
      - aegis_net

  redis:
    image: redis:7-alpine
    container_name: aegis_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - aegis_net

networks:
  aegis_net:
    driver: bridge

volumes:
  redis_data:
